### ISSUE TITLE
복합키 매핑시 equals(), hashCode() 구현 이유 + @EqualsAndHashCode설명

### ISSUE THREAD

**Issue by Bell-Water** [HSU-Bee/server#7]
## JPA에서 복합키 사용시 equals() hashCode()를 구현해야 하는 이유

JPA는 영속성 컨텍스트에 엔티티 보관시 엔티티의 식별자를 키로 사용하고 이를 구분하기 위해 equals와 hashCode를 사용해서 동등성을 비교합니다. 식별자 필드가 하나일 때는 보통 자바의 기본 타입을 사용하므로 문제가 되지 않지만, 식별자 필드가 2개 이상이면 별도의 식별자 클래스를 만들고 그곳에 equals와 hashcode를 구현해야 합니다.

그 이유는 다음과 같습니다. 영속성 컨텍스트 내부에 존재하는 1차 캐시는 해시 맵으로 구현되어 있습니다. (엔티티의 식별자가 키, 엔티티가 값으로 구성) 해시 맵은 두 객체가 동등한지 비교할 때 우선 hashcode() 메소드의 결과인 해시코드 값이 같은지 확인하고, 만약 코드값이 다르면 다른 객체로 판단합니다. 반대로 해시코드 값이 같으면 equals()메소드로 다시 비교하여 이 두 개가 모두 맞아야 비로소 동등 객체로 판단을 합니다. 그러므로 복합키를 영속성 컨텍스트에서 사용하려면 식별자 구분을 위해 equals와 hashCode를 구현해야 합니다.

#### 출처

[[[java] hashcode()와 equals() 메서드는 언제 사용하고 왜 사용할까?](https://jisooo.tistory.com/entry/java-hashcode%EC%99%80-equals-%EB%A9%94%EC%84%9C%EB%93%9C%EB%8A%94-%EC%96%B8%EC%A0%9C-%EC%82%AC%EC%9A%A9%ED%95%98%EA%B3%A0-%EC%99%9C-%EC%82%AC%EC%9A%A9%ED%95%A0%EA%B9%8C)](https://jisooo.tistory.com/entry/java-hashcode%EC%99%80-equals-%EB%A9%94%EC%84%9C%EB%93%9C%EB%8A%94-%EC%96%B8%EC%A0%9C-%EC%82%AC%EC%9A%A9%ED%95%98%EA%B3%A0-%EC%99%9C-%EC%82%AC%EC%9A%A9%ED%95%A0%EA%B9%8C)

[[JPA 기초 3 - 영속성 컨텍스트(Persistence Context) | shirohoo’s Blog](https://shirohoo.github.io/spring/spring-data-jpa/2021-06-23-jpa-3/)](https://shirohoo.github.io/spring/spring-data-jpa/2021-06-23-jpa-3/)

## [@EqualsAndHashCode](https://projectlombok.org/features/EqualsAndHashCode) 동작원리

[@EqualsAndHashCode](https://projectlombok.org/features/EqualsAndHashCode) 어노테이션은 기본적으로 엔티티 내부에 존재하는 non-static, non-transient 필드들을 전부 사용하여 코드를 equals(Object other)와 hashCode() 함수를 작성합니다. (transient는 serialize(직렬화)하는 과정에서 제외하고 싶은 경우 선언하는 키워드, 패스워드 같은 보안정보를 직렬화 과정에서 제외하고 싶은 경우 사용 or 데이터를 전송하고 싶지 않을 때 사용) 하지만 함수 작성시 특정 필드만을 사용하거나 특정 필드를 제거하고 싶다면 필드나 메소드에 include, exclude 지정하면 됩니다.

만약 특정 클래스를 상속받은 엔티티에 아무런 설정없이 이 어노테이션을 사용한다면 상속받은 클래스에 속한 필드는 equals()와 hashcode() 작성시 사용되지 않습니다. 따라서 상속한 클래스의 필드를 포함한 모든 필드를 사용하여 작성되길 원한다면 @EqualsAndHashCode(callSuper = true) 설정을 해야합니다. (상속을 하지 않은 엔티티에 이를 적용시 compile-time error가 발생한다)

### Lombok 사용시

```java
// With Lomok

import lombok.EqualsAndHashCode;

@EqualsAndHashCode
public class EqualsAndHashCodeExample {
  private transient int transientVar = 10;
  private String name;
  private double score;
  @EqualsAndHashCode.Exclude private Shape shape = new Square(5, 10);
  private String[] tags;
  @EqualsAndHashCode.Exclude private int id;
  
  public String getName() {
    return this.name;
  }
  
  @EqualsAndHashCode(callSuper=true)
  public static class Square extends Shape {
    private final int width, height;
    
    public Square(int width, int height) {
      this.width = width;
      this.height = height;
    }
  }
}
```

### Lombok 미사용시

```java
// Vanilla Java
import java.util.Arrays;

public class EqualsAndHashCodeExample {
  private transient int transientVar = 10;
  private String name;
  private double score;
  private Shape shape = new Square(5, 10);
  private String[] tags;
  private int id;
  
  public String getName() {
    return this.name;
  }
  
  @Override public boolean equals(Object o) {
    if (o == this) return true;
    if (!(o instanceof EqualsAndHashCodeExample)) return false;
    EqualsAndHashCodeExample other = (EqualsAndHashCodeExample) o;
    if (!other.canEqual((Object)this)) return false;
    if (this.getName() == null ? other.getName() != null : !this.getName().equals(other.getName())) return false;
    if (Double.compare(this.score, other.score) != 0) return false;
    if (!Arrays.deepEquals(this.tags, other.tags)) return false;
    return true;
  }
  
  @Override public int hashCode() {
    final int PRIME = 59;
    int result = 1;
    final long temp1 = Double.doubleToLongBits(this.score);
    result = (result*PRIME) + (this.name == null ? 43 : this.name.hashCode());
    result = (result*PRIME) + (int)(temp1 ^ (temp1 >>> 32));
    result = (result*PRIME) + Arrays.deepHashCode(this.tags);
    return result;
  }
  
  protected boolean canEqual(Object other) {
    return other instanceof EqualsAndHashCodeExample;
  }
  
  public static class Square extends Shape {
    private final int width, height;
    
    public Square(int width, int height) {
      this.width = width;
      this.height = height;
    }
    
    @Override public boolean equals(Object o) {
      if (o == this) return true;
      if (!(o instanceof Square)) return false;
      Square other = (Square) o;
      if (!other.canEqual((Object)this)) return false;
      if (!super.equals(o)) return false;
      if (this.width != other.width) return false;
      if (this.height != other.height) return false;
      return true;
    }
    
    @Override public int hashCode() {
      final int PRIME = 59;
      int result = 1;
      result = (result*PRIME) + super.hashCode();
      result = (result*PRIME) + this.width;
      result = (result*PRIME) + this.height;
      return result;
    }
    
    protected boolean canEqual(Object other) {
      return other instanceof Square;
    }
  }
}
```

#### 출처

[@EqualsAndHashCode](https://projectlombok.org/features/EqualsAndHashCode) projectlombok사이트

**Comment by HanInJu** [comment]
감사합니다.
